### ISSUE TITLE
Plugin development tutorial: PNG images

### ISSUE THREAD

**Issue by quantumm** [PyMoDAQ/PyMoDAQ#121]
Hi,
It seems like there is a problem with the rendering of some images in the [tutorial](https://pymodaq.cnrs.fr/en/latest/tutorials/plugin_development.html): it seems like some links to PNG images are broken.

It seems like the file extension of some PNG images has been transformed in uppercase in the remote server. But if I build locally there is no problem.

**Comment by quantumm** [comment]
For example in Sec. 4.1.5.4. External open-source libraries. The PyMeasure website capture is not rendered.

**Comment by seb5g** [comment]
This is an issue I already saw. The server that builds the docs runs on linux and it is important there to respect upper or lower case extensions while windows doesn't care... So locally you can build it seamlessly because you're running on windows! Could you crosscheck which images are not ok on the website and chnage the extension of those accordingly in the source?

**Comment by seb5g** [comment]
and the capture tool from windows add PNG upper case as default...

**Comment by seb5g** [comment]
well I don't think it changed the case, it's just that some images were saved with *.png and some other as *.PNG but if in the source code, you call .png for a .PNG file, linux will complain while windows won't...

**Comment by quantumm** [comment]
I am quite sure it did actually. Anyway i made a PR #122 with all file extensions .png lowercase.
I hope it will solve the problem.

**Comment by seb5g** [comment]
ok if you say so, that's strange but the PR should solve the problem!
