### ISSUE TITLE
How to user control a ParameterTree settings in a daq_viewer when grabbing data?

### ISSUE THREAD

**Issue by Ashwolaa** [PyMoDAQ/PyMoDAQ#176]
I thought you could change the parameter tree settings  in a daq_viewer during an acquisition (aka a grab_data)
Is there a way to do it?

Otherwise, I think this should be restored and maybe given as an additional key entry to check if the parameterItem can be accessed and changed during a grab_data or not.

In my application, I would like to scan the trigger level of a scope for example or change the vertical/division in a specific channel. 

Edit: Being able to scroll down in the parameterTree would also be great

**Comment by seb5g** [comment]
I removed that feature because I thought it would make things buggy in some cases. If you wish we could easily put the option in the config file. The option to change the settings during a grab would not be allowed by default, but an advanced user could configure to do so. 

In the meantime, you can just comment this line to allow the settings editing during grab:
![image](https://github.com/PyMoDAQ/PyMoDAQ/assets/6609955/f9e8f558-4d32-47eb-9fb7-d79069b32034)
