### ISSUE TITLE
Release of h5 files while using the do scan extension 

### ISSUE THREAD

**Issue by hugomarroux** [PyMoDAQ/PyMoDAQ#187]
When scanning of even between scans it seems impossible to read the content of the h5 file with another application (like HDFview). We can only acces it when we shut down the doscan extension and the dashboard. Is it possible to have access to the file with the doscan open and even when scanning ? In our case we want to apply some home coded python script to visualize the data and apply specific teatments.

**Comment by seb5g** [comment]
Yes this is a known limitation at the moment, I'll have to look into it especially because even when the scan is done or working on another dataset one still can't use externally the file.

As for reading during a scan I strongly advise against it, you don't want to corrupt the memory of your data. Make just sure the live info you're plotting are enough to get a good overview of what's going on. and if it's not enough, build an extension to be run on top of the daq_scan, you'll have then access to real time data!

**Comment by BenediktBurger** [comment]
I looked into the documentation of pytables. They state, that it is possible to read a file from another thread, however you they strongly advise against it. The reason is, that if you read during a write process, you might get a corrupted table / array.

Pymodaq could close the file after a scan and reopen it later again. If I understand correctly, opening a file should be quite fast, as it is only read if needed.

**Comment by francoisBmallet** [comment]
I have just moved from pymodaq3 to pymodaq4 my whole experiment and really enjoying it thanks. However I am facing this issue which was not in version 3. Would it be possible to have external access to previous dataseT when a new dataset has been openned without having to shut done the dashboard ?

**Comment by seb5g** [comment]
I didn't have the time to work on that yet. But somehow the reference of the file that is shared among threads is preventing the proper closing/flushing of the reference preventing the opening out of the current dashboard instance. It is different from pymo3 because now control modules share the hdf5 instance directly writing into it (no more the daq_scan extension). Maybe we should try to make control modules "forget" about this reference to allow the file to be opened elsewhere. Should try to produce a minimal working example...

**Comment by loicguilmard** [comment]
What about using this new hdf5 features : Single Writer Multiple Reader (SWMR)
https://docs.h5py.org/en/stable/swmr.html

**Comment by seb5g** [comment]
This is an old feature for multi process but the latest changelog from tables started: 
![Screenshot_20240621-075921](https://github.com/PyMoDAQ/PyMoDAQ/assets/6609955/b5f1afdc-abc1-43ab-a990-3aaf596e4461)

**Comment by seb5g** [comment]
What we need is a minimal working example to test why and how to solve this. I have a feeling it is related to me passing the h5 file reference to daq viewer and letting them write their data in their dedicated nodes. It is not creating write issues as far as I know but somehow prevent the release of the reference. It would still be possible to do all the saving only in the daq scan if needed

**Comment by seb5g** [comment]
I worked on a solution in PR #347 . Everyone interested, could you test the implementation (test pymodaq from the branch : https://github.com/PyMoDAQ/PyMoDAQ/tree/bugfix/release_hdf5_file_ref and leave comments here or on the PR!!

**Comment by francoisBmallet** [comment]
I've just tried it. As far as I'm concerned, this bug is fixed. 'read' access to the current h5 file is allowed as soon as the scan is over perfect thanks !

**Comment by seb5g** [comment]
Make sure to properly check the content of the HDF5 files and make sure it corresponds exactly at what it should be on a few examples on your setup please

**Comment by francoisBmallet** [comment]
I did it with mocks first and then with my own actuators and detectors and I have noticed no issue on both. The content of the h5 file is correct on both cases (data and attributes)

**Comment by seb5g** [comment]
I'm closing the issue as the implementation #347 seems to work
