### ISSUE TITLE
Averaging data in a scan

### ISSUE THREAD

**Issue by hugomarroux** [PyMoDAQ/PyMoDAQ#194]
Hello all, 

I was wondering if there is a easy way to average data at the step of a scan rather than taking a single aquisition and then moving to the next step? I have tried to increase the averaging in the viewer but it seems that in the scan this parameter is not used. 

Thanks 

Hugo

**Comment by rgeneaux** [comment]
Hi,
This was a bug that got fixed in commit 08dac95658c6924e78a67b2de949e676618f21a7
So either wait for version 4.0.9 to release (it will include the bug fix) or install pymodaq from git to get the latest version:
`pip install --force-reinstall --no-deps git+https://github.com/PyMoDAQ/PyMoDAQ`
(if you don't put the force reinstall, pip will see that you already have 4.0.8 and so it wo'nt actually update)

**Comment by seb5g** [comment]
By the way I think it is time to prepare a new release,  so I prepared a new branch called 4.1.0 (for the futur release) to be tested (together with beta release 4.1.0.beta). It means that PR related to bug fixes of its new features will be pushed on this branch, while we keep pymodaq_dev for more new functionnalities. You have then 2 possibilities: either install from the 4.1.0 branch or from the beta release: `pip install pymodaq==4.1.0.beta` . If there are things to discuss about it there is a discussion on the subject.

**Comment by hugomarroux** [comment]
Hello thanks for the answer. I have updated to the beta version and I'll let you know if we run into some troubles.
Cheers

Hugo

**Comment by seb5g** [comment]
ok for the moment I'll close the issue then, if you see anything not working, just reopen it!
