### ISSUE TITLE
file name / path as command line parameter for h5browser?

### ISSUE THREAD

**Issue by bernhardlang** [PyMoDAQ/PyMoDAQ#260]
When launching the h5browser, a file-open dialog pops up pointing to the root directory. Depending on how many files one wants to inspect and how deep the tree is, it becomes quickly rather tedious to brachiate each time through half the forest. Therefore I added a few lines to browsing.py and h5browser.py so that the command python -m pymodaq.extensions.h5browser my-data-file.h5 will open that file directly if it exists or come up with the file dialog pointing to the corresponding path if the latter exists, otherwise the longest valid parent path. Questions:

a) Would that be of more general interest? Should I launch a merge request to the dev branch after having done some testing?

b) If yes, "Open if existing or else ask what to open" with sensible default path options sounds like a rather generic task. Could be useful in various other places. Should that rather go to some utils module?

c) Related to working on that: after having forked PyMoDAQ, cloned it locally and checked out 4.2.x_dev, resources/VERSION contains still 4.1. is that intentional?

d) When starting the dashboard in the virtual environment where the 4.2.x_dev branch is installed as editable, a message pops up that a new version of PyMoDAQ would be available. When accepting to upgrade, the editable version 4.2.x_dev gets replaced by 4.1.1 (the git repository still being there untouched but dismissed for python in favour of the newly installed 4.1.1 in the site-packages).

e) Should I raise the latter two items elsewhere?

**Comment by rgeneaux** [comment]
Hi Bernhard,
I was surprised that you had to add those these lines since I remember doing that some time ago (found it: https://github.com/PyMoDAQ/PyMoDAQ/pull/76/commits/0f2dbd8ec78eb9dd78e4f6ba69cc29f7544fc986) but it looks like my changes and the documentation got lost at some point!!
a) So yes, this is of general interest and we should put it back into the dev branch.
c) No but this just got fixed 2h ago!
d) This is related to (c), with the proper VERSION file, the "new version is availble" popup should not appear

**Comment by seb5g** [comment]
I was just going to say all that :-)

**Comment by seb5g** [comment]
I'll bring back your previous commit into the current branches, somehow it stayed with the v3 branch

**Comment by seb5g** [comment]
PR #261 is retauring your commit . @rgeneaux  can you review it?
