### ISSUE TITLE
H5 content definition

### ISSUE THREAD

**Issue by BenediktBurger** [PyMoDAQ/PyMoDAQ#312]
I'm looking into hdf5 file format to store my data (acquired via Pyleco) 
Is there a specification you follow for the pymodaq save mechanism?

Even if you made your one up, it could be good to adapt your one for better interoperability of data viewers (browsers).

Thanks!

**Comment by seb5g** [comment]
Yes I produced a complete framework both for data management (object and their manipulation, even plotting: http://pymodaq.cnrs.fr/en/latest/user_folder/data_management.html) and their corresponding structure within h5 file (http://pymodaq.cnrs.fr/en/latest/user_folder/data_management/saving_loading_data.html). This allows a seamless integration of pymodaq data into and from hdf5.

The saving objects implement the specification which is otherwise not really specified. But the interop is made by creating PyMoDAQ data objects first (even from other data source) and then resaving them in hdf5 if needed

I'm even thinking to pull this framework out of pymodaq  to make it independent and a package people could use to store/manipulate physical data. Would you be interested in that?

**Comment by BenediktBurger** [comment]
> I'm even thinking to pull this framework out of pymodaq to make it independent and a package people could use to store/manipulate physical data. Would you be interested in that?

That would be nice.
That way not everybody has to invent their own scheme, nor their own data browser.

> The saving objects implement the specification which is otherwise not really specified. But the interop is made by creating PyMoDAQ data objects first (even from other data source) and then resaving them in hdf5 if needed

I see, thanks!

I'm also interested in a continuous measurement, adding row after row, not just the final table. Is that already possible within your framework?

**Comment by seb5g** [comment]
Sure this is an extendable saving object. Already used in pymodaq with the
continuous saving mode of the daqviewers or the daqlogger extension

Le mer. 5 juin 2024, 08:54, Benedikt Burger ***@***.***> a
écrit :
