### ISSUE TITLE
DAQ_Move: the user should press Enter in the green or red boxes for the value to be taken into account

### ISSUE THREAD

**Issue by quantumm** [PyMoDAQ/PyMoDAQ#329]

**Comment by bernhardlang** [comment]
QSpinBox emits two different signals upon user interaction: a) valueChanged each time the user enters a character which is accepted, b) editingFinished when either Enter is pressed or the spin box looses the focus. Unfortunately, when clicking a QPushButton, the focus lost event is sent to the spin box _after_ the clicked signal of the button is emitted. Therefore, when using editingFinished to propagate the value of the spin box, the receiver may not be up to date when the button is clicked.
Proposed solution in case this is the origin of the problem: when the user clicks an arrow button, read the current value of the corresponding spin box directly from the spin box instead of using the value obtained from the signal editingFinished.
