### ISSUE TITLE
Move serializer to data package

### ISSUE THREAD

**Issue by BenediktBurger** [PyMoDAQ/PyMoDAQ#431]
I realized for my qt-less example, that we need the serializer in many cases (if the user uses a data_with_axes object to control an actuator, or to send a detector image back).

Therefore it would be good, if a qt-less serializer were available.

**Comment by seb5g** [comment]
I thought about this before, but then thought this serializer would only be needed by the pymodaq highest level features. And I was reluctant because PyMoDAQ introduces three specific data objects: DataActuator, DataFromPlugins and DataToActuators deriving from dwa and dte. I'm not sure if this is really a problem but they have to be in the namespace (imported) when the deserializer works on them (and even in the DwaTypes enum):

```
        class_name = self.string_deserialization()
        if class_name not in DwaType.names():
            raise TypeError(f'Attempting to deserialize a DataWithAxes flavor but got the bytes for a {class_name}')
        timestamp = self.scalar_deserialization()
        try:
            dwa_class = getattr(data_mod, class_name)
        except AttributeError:  # in case it is a particular data object defined only in pymodaq
            dwa_class = getattr(data_mod_pymodaq, class_name)
        dwa = dwa_class(self.string_deserialization(),
```

this should be worked on before attempting to move the guy in pymodaq_data.

**Comment by seb5g** [comment]
actually I moved the dwaTypes in pymodaq_data and so far left the particular object in there... this is a bit of a dirty mixedup... 

maybe we should just use a dwa factory, and register any specific implementation. like this we don't need the dwatypes enum but just a proper registration of dwa/dte objects. 

Actually I did something similar in DataBase class for it and its children to not be wrapped by pint:

```
    def __new__(cls, *args, **kwargs):
        if not pint.compat.is_upcast_type(cls):
            upcast_type_map.update({f'{cls.__module__}.{cls.__name__}': None})
            # this will make sure, these
            # objects are not wrapped by pint
        return super().__new__(cls)

```

putting a registration in the __new__ method similarly would add any children class! no need for people to call registration on their reimplementation!!

**Comment by seb5g** [comment]
Hi @BenediktBurger 

I fully reimplemented the serializing stuff using a factory pattern. Object to be serialized are registered either "manually" for the case of builtins or using decorator/methods in their __new__ method. This allows all child class of such objects to be automatically registered, for instance DataActuator that lives on the pymodaq package and not on the pymodaq_data. The pymodaq object to be serialized expose two methods: serialize and deserialize implementing a base class interface defined in the factory module. 

Then all serialization/deserialization can be done using the factory special methods:

```
def test_axis_serialization_deserialization():

    axis = init_axis()

    ser = axis.serialize(axis)
    assert isinstance(ser, bytes)

    axis_deser = axis.deserialize(ser)[0]
    assert axis_deser == axis

    axis_back = ser_factory.get_apply_deserializer(ser_factory.get_apply_serializer(axis))[0]
    assert axis_back == axis
```

those are:
* get_apply_serializer
* get_apply_deserializer

a method allows to check if a type is registered: **get_serializables**

You will be able to comprehend it more from the test suite and looking into the serializer module. If not, ask me. 

Everything has been moved into the pymodaq_data.serialize module.  The Serializer and Deserializer are in the serializer_legacy module but should not be used anymore because the factory provides the necessary introspection. The object type is now encoded in the bytes, therefore the factory knows which registered serializer/deserializer methods to call.

This should ease the development and use of these guys without the need for your SERIALIZABLES type and DwaTypes.

Now you have to work on the dedicated branch: feature/serializer (both in pymodaq, pymodaq_data and pymodaq_gui (for the registration of the ParameterWithPath object). To ease the work on all those repo and synchronize them I used the utils called [mu-repo](https://github.com/fabioz/mu-repo), quite nice and easy to use. You'll have to do so in order to move the leco base stuff from pymodaq to pymodaq_data!

**Comment by BenediktBurger** [comment]
Very interesting.

I'll have a look next week  and will tackle the issue then.

**Comment by BenediktBurger** [comment]
> axis_deser = axis.deserialize(ser)[0]

Isn't this additional index overly complex?
I understand that manual decoding does allow to return the left over bytes, but normally, you expect to get the full object, don't you?
If you want to check, whether you got everything, you could add a check, that there are no bytes left after you deserialized an object.

**Comment by BenediktBurger** [comment]
Anyhow, do you wish me anything to do?

Once this new serializer is in main, we can close this issue.

**Comment by seb5g** [comment]
> > axis_deser = axis.deserialize(ser)[0]
> 
> Isn't this additional index overly complex? I understand that manual decoding does allow to return the left over bytes, but normally, you expect to get the full object, don't you? If you want to check, whether you got everything, you could add a check, that there are no bytes left after you deserialized an object.

this would mean that sometimes you return just the object and sometimes also the leftover bytes? I had this because when using basic sockets you don't know if everything has been transmited yet. Of course with pyleco and zmq, this is not the case anymore... Would a check and two types of return be acceptable?

**Comment by seb5g** [comment]
by the way the new serializer/deserializer is now in pymodaq_data main branch (even on pypi). It would be nice if you could change the use of it (imports mostly) whenever they are needed in pymodaq v5. Maybe after we are done about the discussion concerning the return type of the deserializer?

**Comment by BenediktBurger** [comment]
> this would mean that sometimes you return just the object and sometimes also the leftover bytes? I had this because when using basic sockets you don't know if everything has been transmited yet. Of course with pyleco and zmq, this is not the case anymore... Would a check and two types of return be acceptable?

My idea:
- `deserialize(bytes_object)` will return the corresponding object only and will check that there are no bytes left.
- `deserialize(bytes_object, additional_bytes=True)` will return a tuple of the object and additional bytes.
- Optionally, you could make two methods `deserialize_bytes -> tuple[object, bytes]` and `deserialize`, which just calls the former one, checking, that bytes_object is empty. Actually, this second method could be defined in `SerializableBase`, as it is the same for all serializable classes.

That makes it more understandable in the common case of deserialization of an object, but allows the flexibility to deserialize only a part.

**Comment by seb5g** [comment]
I agree with option two. I will make the change and let you know when this is released for modifications in pymodaq leco

**Comment by seb5g** [comment]
well I was on the go then realized I already took care of this. if you just use the factory to deserialize then you just have to call:
```
ser_factory.get_apply_deserializer(bytes_str, only_object=True)
```

to obtain only the object out of deserialization object... Would that be fine?

**Comment by BenediktBurger** [comment]
I'd make that only_object the default, but other than that, that's fine.

**Comment by seb5g** [comment]
Hi. As suggested I flipped the default case to True and adapted the test to this. Both last release of pymodaq_data and pymodaq_gui (for the serialization of ParameterWithPath) are reflecting this. If you're ok, we are closing this issue and open one on the use of this serializer into pyleco communication within pymodaq v5.

**Comment by BenediktBurger** [comment]
Thanks for your work.
I opened a new issue.
