### ISSUE TITLE
Why is the CI runs sometimes failing?

### ISSUE THREAD

**Issue by seb5g** [PyMoDAQ/PyMoDAQ#449]
**Describe the bug**
When pushing new code, CI is running automatic tests. This is fine to discover bugs but sometimes, the run fails due to some random problem on the virtual machine. This sends a bunch of emails we don't even check anymore...

**To Reproduce**
run the CI tests there might be one failing from time to time...

**Expected behavior**
Runs shoud fail only when the tests fails....

**Additional context**
maybe see [this ](https://about.codecov.io/blog/find-failing-and-flaky-tests-with-codecov-test-analytics/?utm_source=email&utm_medium=email&utm_campaign=codecov-fy25q4-testcoverage&utm_content=blog-testanalytics-learnmore&mkt_tok=Nzc2LU1KTi01MDEAAAGWyuorGPbvJV1qPbGpKt188JEpr0Z5euUhlWmJnFNkSJMgSJuFNBC_NGeiJch3hE0mwjtjmAWdZlE8w4F4mt8I34yKmCb4arxwqcbUcOg3ZDo)for a solution?

**Comment by loicguilmard** [comment]
I have another issue with tests. There is a combination where it tries to install pymodaq 4 and 5 in the same environment and fail for that. I am still trying to figure out what is what because requirements looks ok

**Comment by seb5g** [comment]
it may be it doesn't checkout the right branch (maybe only the default) during the install step

**Comment by malik-irain** [comment]
It seems the problem comes from thread-unsafe initialization from pymodaq in combination with multiple threads running tests (`-n auto` argument of pytest), that's why it doesn't always fail. I guess what is happening when it is failing is that one worker (`gw0`) would import something and start some initialization from an `__init__.py` file, be interrupted by the other (`gw1`) in the middle of it. `gw1` would then try to import the same module but will not run __init__.py as it is always running (by `gw0`) but it should only be done once. As `gw0` initialization is not complete, some names are not available from the imported module, hence the import errors in `gw1`. 

I made a PR to address the problem at the cost of running the tests with only one worker.

Some more investigation should be done in order be able to use multiple workers to run tests.

**Comment by seb5g** [comment]
good one, all the tests pass! Nice first PR @malik-irain
