### ISSUE TITLE
Tests of h5modules

### ISSUE THREAD

**Issue by LMSC-NTappy** [PyMoDAQ/PyMoDAQ#91]
Hello @seb5g,

I started working on an improved export feature with new files formats. I figured out verifying tests would be a good starting point. I noticed that most lines in the test file are commented out: 

https://github.com/PyMoDAQ/PyMoDAQ/blob/90cae4a78691cb6b9c05116d295ec001b80d823c/tests/daq_utils_test/h5modules_test.py#L127-L139

Any reason why that is? I get passing tests for the H5BrowserUtils

**Comment by seb5g** [comment]
Hello Nico,
Well it's because those tests went a bit messy and because I'm in the process of heavy change to the data saving mechanisms, only the low level tests should be kept. I'll have to do a go around this when I'm getting confident with the new version. Don't worry about your exporting as it is on the higher level objects and if you follow what we said about object factory applied to exporting, that should be easily portable! Maybe you should built those out of the current modules, a bit like a test module...

**Comment by LMSC-NTappy** [comment]
Hey Seb!

fine with me, thanks for the explanations. I reactivated what I need to work with, we'll see how this goes as I progress with the implementation of new exports.

Cheers

Nico
