### ISSUE TITLE
Epsilon parameter of daq_moves is always set to 1 regardless of preset value

### ISSUE THREAD

**Issue by rgeneaux** [PyMoDAQ/PyMoDAQ#96]
Hi guys,

I noticed an issue with daq_move_base: if you create a dashboard preset with an actuator, upon loading epsilon will always be set to 1, regardless of preset value.

It seems like this happens here:
https://github.com/PyMoDAQ/PyMoDAQ/blob/ee72fa5947fc628771b9ad99501c5a3bb54d6268/src/pymodaq/daq_move/utility_classes.py#L158

https://github.com/PyMoDAQ/PyMoDAQ/blob/ee72fa5947fc628771b9ad99501c5a3bb54d6268/src/pymodaq/daq_move/utility_classes.py#L183

I commented line 183 and it seems like it works... but maybe this is meant for something, I'll let you actually fix it instead of breaking something!

**Comment by seb5g** [comment]
Hi guys,
in fact _epsilon should be redefined in all of our plugins as class attributes especially because the one developing the plugin should be the one that knows what value is adequate (depends on the controller). So if someone doesn't know much he won't have to play with _epsilon.

I just added this in the template:
```
# _epsilon is the initial default value for the epsilon parameter allowing pymodaq to know if the controller reached
# the target value. It is the developer responsibility to put here a meaningful value
_epsilon = 0.1  # TODO replace this by a value that is correct depending on your controller
```
that said, if epsilon is set in the preset to a different value compared to the default one (_epsilon), one should probably apply the preset one. I'll propose a pull request in that direction
